baseURL = 'https://mtf-wiki.github.io/blog'
languageCode = 'en-us'
title = 'MtF.wiki Blog'
theme = 'ink-free'
copyright = '&copy; Copyright MtF.wiki'

[params]
wpm = 250

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2
